# Generated by Django 2.1.7 on 2019-03-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='noun',
            field=models.TextField(default='Stranger', verbose_name='greeting noun'),
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
